version: '3.8'
services:
  install:
    image: node:lts-slim
    command: npm install
    working_dir: /app
    volumes:
      - ./:/app

  dev:
    image: node:lts-slim
    command: npm run dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"